### ISSUE TITLE
The latest timestamp of mc4

### ISSUE THREAD

**Issue by EliverQ** [google-research/multilingual-t5#114]
Apologize for troubling you with this matter. In your paper, you mention that "we make use of all of the 71 monthly web scrapes released so far by Common Crawl." but I am unsure about the exact starting time.
<img width="612" alt="image" src="https://user-images.githubusercontent.com/37859378/231096323-db8403ab-1a09-4f9c-8e0d-1b40e3fb2aee.png">
Dou you mean 2014/03 or 2008? I would greatly appreciate it if you could provide me with information regarding this matter.

**Comment by craffel** [comment]
See https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/text/c4.py#L146
