### ISSUE TITLE
can't reproduce finetuning task via colab

### ISSUE THREAD

**Issue by acul3** [google-research/multilingual-t5#13]
hi,,
i'm  trying to reproduce fine tuning task on colab(base on this https://github.com/google-research/text-to-text-transfer-transformer/tree/master/notebooks) but got some error when trying to execute finetune model

i'm adding task and mixture by using sample from https://github.com/google-research/multilingual-t5/blob/master/multilingual_t5/tasks.py

error show when finetune command executed, it says:

for xnli mixture
```
/usr/local/lib/python3.6/dist-packages/tensorflow_datasets/core/features/text_feature.py in from_json_content(cls, value)
    183     if "use_encoder" in value:
    184       raise ValueError(
--> 185           "Deprecated encoder not supported. Please use the plain text version "
    186           "with `tensorflow_text`."
    187       )

ValueError: Deprecated encoder not supported. Please use the plain text version with `tensorflow_text`.
  In call to configurable 'mesh_train_dataset_fn' (<function mesh_train_dataset_fn at 0x7fcd13c28378>)
```

for tydiqa mixture
```
Tensor-typed variable initializers must either be wrapped in an init_scope or callable (e.g., `tf.Variable(lambda : tf.truncated_normal([10, 40]))`) when building functions. Please file a feature request if this restriction inconveniences you.
```

here my google colab if you guys dont mind to look at it:
https://colab.research.google.com/drive/12a4ZgJUI6XRzkc0ZiFyuYiFWpCiiXSde?usp=sharing

thanks before

**Comment by adarob** [comment]
@Conchylicultor FYI

**Comment by acul3** [comment]
i manage to bypass  Deprecated encoder error
after change mnli tfds name in [task.py](https://github.com/google-research/multilingual-t5/blob/dc59219241a294a78077ea1bea26fd61326a1147/multilingual_t5/tasks.py#L119)  from `multi_nli/plain_text:1.0.0` to `multi_nli`  and remove `:` restriction in [dataset_provider.py](https://github.com/google-research/text-to-text-transfer-transformer/blob/68b75d9a004695c795721b6faa0237e265292af4/t5/data/dataset_providers.py#L715)

but still got the 

```
Tensor-typed variable initializers must either be wrapped in an init_scope or callable (e.g., `tf.Variable(lambda : tf.truncated_normal([10, 40]))`) when building functions. Please file a feature request if this restriction inconveniences you.
```

after that

**Comment by adarob** [comment]
This will be fixed in https://github.com/tensorflow/datasets/pull/2679
Thanks for reporting!
