### ISSUE TITLE
checkpoint file size varies

### ISSUE THREAD

**Issue by ashissamal** [google-research/multilingual-t5#14]
I could see the checkpoint file size varies within the mT5-base. Like wise, it is also observed for mT5-large models. 
Is there any specific reason for this ?

PS: I am not referring the checkpoint file size difference between mT5-base and mT5-large, which is expected.

**Comment by adarob** [comment]
Are you referring to the size of the shards? There is only one released checkpoint per model.

**Comment by ashissamal** [comment]
Thanks. I could realize its the size of shards. Why did not you share the checkpoint in one shard ?

**Comment by adarob** [comment]
It was trained with model parallelism so I believe this is simply how the parameters were sharded during pre-training. It also makes it faster to restore the parameters since they can be loaded in parallel.
