### ISSUE TITLE
can't finetune on gpu

### ISSUE THREAD

**Issue by SarraCode** [google-research/multilingual-t5#18]
Hello,
Congratulations and thank you for your contribution.
I am trying to fine tune mT5 on a my dataset but I couldn't make it work, I am installing T5 via pip install but it has not an explicit requirement on tensorflow versions. I tried some solutions on the t5 repo but none worked. Any help is appreciated. 

and pip packages:

 cuda/10.1
cudnn/7.6-cuda-10.1
```
Package                  Version
------------------------ ---------------------
absl-py                  0.11.0
astunparse               1.6.3
attrs                    20.2.0
Babel                    2.8.0
cachetools               4.1.1
certifi                  2020.6.20
chardet                  3.0.4
click                    7.1.2
dataclasses              0.7
dill                     0.3.3
dm-tree                  0.1.5
filelock                 3.0.12
future                   0.18.2
gast                     0.3.3
gin-config               0.3.0
google-auth              1.23.0
google-auth-oauthlib     0.4.2
google-pasta             0.2.0
googleapis-common-protos 1.52.0
grpcio                   1.33.2
h5py                     2.10.0
idna                     2.10
importlib-metadata       2.0.0
importlib-resources      3.3.0
joblib                   0.17.0
Keras-Preprocessing      1.1.2
Markdown                 3.3.3
mesh-tensorflow          0.1.17
nltk                     3.5
numpy                    1.19.4
oauthlib                 3.1.0
opt-einsum               3.3.0
packaging                20.4
pandas                   1.1.4
pip                      20.2.4
portalocker              2.0.0
promise                  2.3
protobuf                 3.13.0
pyasn1                   0.4.8
pyasn1-modules           0.2.8
pyparsing                2.4.7
python-dateutil          2.8.1
pytz                     2020.4
regex                    2020.10.28
requests                 2.24.0
requests-oauthlib        1.3.0
rouge-score              0.0.4
rsa                      4.6
sacrebleu                1.4.14
sacremoses               0.0.43
scikit-learn             0.23.2
scipy                    1.5.3
sentencepiece            0.1.94
setuptools               50.3.0.post20201103
six                      1.15.0
t5                       0.7.1
tensorboard              2.3.0
tensorboard-plugin-wit   1.7.0
tensorflow               2.3.1
tensorflow-datasets      4.0.1
tensorflow-estimator     2.3.0
tensorflow-metadata      0.25.0
tensorflow-text          2.3.0
termcolor                1.1.0
tfds-nightly             4.0.1.dev202011030854
threadpoolctl            2.1.0
tokenizers               0.9.2
torch                    1.7.0
tqdm                     4.51.0
transformers             3.4.0
typing-extensions        3.7.4.3
urllib3                  1.25.11
Werkzeug                 1.0.1
wheel                    0.35.1
wrapt                    1.12.1
zipp                     3.4.0
```
Thank you in advance
@adarob

**Comment by SarraCode** [comment]
This is the command i use for finetuning
`PRETRAINED_DIR=gs://t5-data/pretrained_models/mt5/small
PRETRAINED_STEPS=1000000
FINETUNE_STEPS=20000
MODEL_DIR="//models

# Run fine-tuning
t5_mesh_transformer \
  --model_dir="${MODEL_DIR}" \
  --gin_file="${PRETRAINED_DIR}/operative_config.gin" \
  --gin_file="sequence_lengths/xquad.gin" \
  --gin_param="utils.run.train_dataset_fn = @t5.models.mesh_transformer.tsv_dataset_fn" \
  --gin_param="tsv_dataset_fn.filename = '/t5-train/multilingual-t5/test.tsv'" \
  --gin_param="utils.run.train_steps=$((PRETRAINED_STEPS+FINETUNE_STEPS))" \
  --gin_param="utils.run.init_checkpoint='${PRETRAINED_DIR}/model.ckpt-${PRETRAINED_STEPS}'" \
  --gin_param="utils.run.mesh_shape = 'model:1,batch:1'" \
  --gin_param="utils.run.mesh_devices = ['gpu:1']" \
  --gin_location_prefix="multilingual_t5/gin/"`

**Comment by lablebi96** [comment]
Hello, 
Thank you for sharing these details, I have exactly the same problem as you and I am still stack on it. Any help will be appreciated ! I'll keep an eye on this issue !
Please if u find the solution keep me updated
