### ISSUE TITLE
mT5 sentence piece tokenizer

### ISSUE THREAD

**Issue by patrickvonplaten** [google-research/multilingual-t5#24]
Hey guys,

Thanks for open-sourcing mT5!
Is it maybe possible to provide a link to the sentence piece model file that is used for the pre-trained mT5 checkpoints? 
I could not find the file anywhere in the provided checkpoint links.

**Comment by agemagician** [comment]
Hi @patrickvonplaten ,

I think this is what you are looking for:
https://console.cloud.google.com/storage/browser/t5-data/vocabs/mc4.250000.100extra

According to :
https://github.com/google-research/multilingual-t5/blob/master/multilingual_t5/tasks.py

**Comment by craffel** [comment]
Yes, @agemagician's got it.

**Comment by StephennFernandes** [comment]
@agemagician Hey, by any chance would you know how does the mt5 sentencepiece tokenizer have those extra_ids by default ? 

what i need is: **how do i too add the extra_ids already  for the tokenizer such that i could keep the extra_ids=0**

I've been seeing in the mt5 tokenizer the extra 100 ids needed for the sentinel tokens come already included in the tokenizer. 
`'gs://t5-data/vocabs/mc4.250000.100extra/sentencepiece.model'` 

how do i too train my own sentencepiece tokenizer where i could too include the 100extra already in my tokenizer, just like the original one above.

as i am training a variant of mt5 that covers multiple langugaes that the common mt5 does cover. i went on to training a unigram sentencpiece tokenizer with 250000 vocab_size but i tripped into confusion, on how to get the 100 extra_ids similar the the official mt5 tokenizer.

**Comment by StephennFernandes** [comment]
Hey @Adam Roberts. Thanks a ton for your time and helping me out on this issue. 

however could you please confirm if this configuration of training the sentencpiece tokenizer for the mt5 is the appropriate option. 
or do i need to change any args. 

(I just need to exactly train the sentencepiece tokenizer as it was trained for mt5.   ps:  im scared i might do something wrong and irrelavant.)

```
path=/home/stephen/storage_bucket/corpus_text
spm_train --input=$path/large_corpus.txt, --model_prefix=ciil_50M_mt5_spm_250000_unigram --vocab_size=250000 --character_coverage=0.9995 --model_type=unigram --num_threads=128 --byte_fallback=true --train_extremely_large_corpus=true

```
