### ISSUE TITLE
The layer structure of the mT5 model

### ISSUE THREAD

**Issue by rk0033** [google-research/multilingual-t5#40]
I want to understand the layer structure of the mT5 model from the source code.
Should I look at the source below?
https://github.com/google-research/text-to-text-transfer-transformer/blob/a7539e027d5bda36baf5bc9acd55ceb0cb4add5d/t5/models/mtf_model.py#L44

**Comment by craffel** [comment]
No, that is just the interface to the model code. The model code is here: https://github.com/tensorflow/mesh/tree/master/mesh_tensorflow/transformer

**Comment by rk0033** [comment]
@craffel 
Thank you!
To understand the layer structure of mT5 concretely, should I look at the following file and lines?

https://github.com/tensorflow/mesh/blob/master/mesh_tensorflow/transformer/transformer.py
Lines 340 To 354
```
    The default sublayers specified in defaults.gin are:
      transformer.LayerStack.sublayers_initial = [
          @transformer.sublayer_dropout,
      ]
      transformer.LayerStack.sublayers_per_layer = [
          @transformer.sublayer_rms_norm,
          @transformer.sublayer_call_layer,
          @transformer.sublayer_dropout,
          @transformer.sublayer_residual,
      ]
      transformer.LayerStack.sublayers_final = [
          @transformer.sublayer_rms_norm,
          @transformer.sublayer_dropout,
      ]
```

**Comment by craffel** [comment]
You can look at the operative config https://console.cloud.google.com/storage/browser/_details/t5-data/pretrained_models/mt5/base/operative_config.gin

**Comment by rk0033** [comment]
@craffel 
Thank you very much!
Does it mean that the mT5 model is composed of layers such as "Self Attention", "EncDec Attention", and "Dense Relu Dense" described in operative_config.gin?

**Comment by craffel** [comment]
Yes.
