### ISSUE TITLE
The model type of mT5

### ISSUE THREAD

**Issue by rk0033** [google-research/multilingual-t5#41]
According to the source code below, I think there are five model types of transformers below.

https://github.com/tensorflow/mesh/blob/master/mesh_tensorflow/transformer/utils.py

- bitransformer
- lm
- delimited_lm
- aligned
- aligned

Which is the model type of mt5?

**Comment by craffel** [comment]
It is a Bitransformer, see https://console.cloud.google.com/storage/browser/_details/t5-data/pretrained_models/mt5/base/operative_config.gin under "run.model_type"
