### ISSUE TITLE
how to test mT5 on NER tasks 

### ISSUE THREAD

**Issue by ghost** [google-research/multilingual-t5#53]
Hi 
I'd like to test T5 on the WikiAnn NER tasks in the paper, I checked the tasks and to me NER ones are not added, could you assist me with sharing with me how I can add them and test mT5 on NER task? thanks

**Comment by dorooddorood606** [comment]
Hi, same question here, could you please help in including "WikiAnn-NER" to facilitate testing mt5 model on this task? thank you for your help.

**Comment by MGithubGA** [comment]
I also have the same question. Dose it directly decodes the tag sequences in a seq2seq style without any constraints? It seems time-consuming for long sentences.

Thanks @craffel !

**Comment by nconstant-google** [comment]
The WikiAnn NER task has been added here:
https://github.com/google-research/multilingual-t5/blob/master/multilingual_t5/tasks.py#L446
