### ISSUE TITLE
any plan to train mt5 on a similar setup as XLM-R ? 

### ISSUE THREAD

**Issue by rabeehk** [google-research/multilingual-t5#54]
Hi
I just have a general question, mT5 is a very cool model, for being very general, but if it could reach the performance of XLM-R with the same number of parameters it was even better,  I was wondering if you have any plan to train mT5 model on a similar setup as XLM-R and releasing the models in near future? thanks

**Comment by craffel** [comment]
No, we don't have any plans to release such a model.

**Comment by rabeehk** [comment]
thanks for the response.
