### ISSUE TITLE
why it has two DenseReluDense/wi kernel?

### ISSUE THREAD

**Issue by bojone** [google-research/multilingual-t5#6]
In T5, there is just one DenseReluDense/wi kernel like `encoder/block_000/layer_001/DenseReluDense/wi/kernel`, but it is two in MT5 (`encoder/block_000/layer_001/DenseReluDense/wi_0/kernel` and `encoder/block_000/layer_001/DenseReluDense/wi_0/kernel`). Can you suggest me where changes, please?

**Comment by lintingxue** [comment]
Hi, T5 model uses the T5.1.0 architecture, while mT5 adopts T5.1.1, we mentioned this in Section 3.2  in the paper. 

All motel architectures are [here](https://github.com/google-research/text-to-text-transfer-transformer/tree/master/t5/models/gin/models).

**Comment by bojone** [comment]
Thanks a lot. Let me have a try.
