### ISSUE TITLE
including NER tasks

### ISSUE THREAD

**Issue by dorost1234** [google-research/multilingual-t5#60]
Hi
I would need to run the mt5 model on NER tasks, could you please help adding them? thanks

**Comment by dorost1234** [comment]
Hi there, 
I was wondering if you could add these tasks, I have a deadline and need to compare with the MT5 work, thank you very much in advance. @craffel

**Comment by nconstant-google** [comment]
The WikiAnn NER task has been added here:
https://github.com/google-research/multilingual-t5/blob/master/multilingual_t5/tasks.py#L446
