### ISSUE TITLE
number of steps for finetuning

### ISSUE THREAD

**Issue by dorost1234** [google-research/multilingual-t5#64]
Hi
could you clarify for how many steps you finetuned the model for the zero-shot results ?
I do not see this number being reported in the paper, thanks @craffel  @nconstant-google

**Comment by nconstant-google** [comment]
We fine-tuned 20k steps for the NER and the QA tasks, and 10k steps for the other tasks. Note, we selected the best checkpoints based on validation performance, rather than just using the final checkpoint.
