### ISSUE TITLE
evaluation for MLQA in MT5

### ISSUE THREAD

**Issue by dorost1234** [google-research/multilingual-t5#67]
Hi
I have some questions on MLQA evaluation, It seems to me that in mt5 durnig applying squad preprocessor, you choose only the first answer as the selected answer [1]

1) why mt5 do not consider all the answers? 
2) how one can handle multiple answers with mt5 model? how should I form the sequence to sequence format in this case?
3) during the evaluation to me, you consider to have multiple answers [2], at least targets and predictions are a list here, which makes it confused as only the first answer seems to be passed to the script from the beginning, also I am not sure how mt5 returns back a list? could you clarify this please?

thank you @nconstant-google 

[1] https://github.com/google-research/multilingual-t5/blob/a694d1af8d52de5c46b649cb1b9e3b0ba8405a88/multilingual_t5/preprocessors.py#L181 
[2] https://github.com/google-research/text-to-text-transfer-transformer/blob/732efb09be3c6ed9b2d0d1b3e6ac45f08e15989a/t5/evaluation/qa_utils.py#L89

**Comment by craffel** [comment]
Question-answering datasets sometimes have multiple answers annotated. During training, we generally find that choosing the first answer works as well as choosing a random answer. During evaluation, the eval metrics are defined w.r.t. the model's predictions against all possible answers, so we need to retain and use all possible answers.

**Comment by dorost1234** [comment]
Dear Colin
thanks for the reply, then this means that in case of multiple answers, mt5
would get the score of zero? since in the evaluation I see you check that
length of predictions should match, then this means it would never match,
and mt5 can only do a single prediction? is this correct? thanks for your
help

**Comment by craffel** [comment]
No, evaluation on these tasks is defined as comparing the model's prediction to each answer and reporting the highest score among annotated answers.

**Comment by dorost1234** [comment]
Now I see thank you very much
